import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Nav from "@/components/Nav";
import { Toaster } from "sonner";
import "./globals.css";
import { SidebarProviderWrapper, AppSidebar } from "@/components/Sidebar/SideBar";
import { SidebarTrigger } from "@/components/ui/sidebar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} italiana-regular antialiased bg-[#F9F9F9]`}
      >
        <SidebarProviderWrapper>
          <AppSidebar />
          <main className=" bg-slate-100 w-full">
            <SidebarTrigger />
            {children}
          </main>
        </SidebarProviderWrapper>
        <Toaster />
      </body>
    </html>
  );
}
